version: '3'

services:
  redis:
    restart: always
    image: redis
    env_file:
      - ./.env.development
    ports:
      - "6380:6379"
  mysql:
    restart: always
    image: mysql:5.7
    command: --max_allowed_packet=32505856
    env_file:
      - ./.env.development
    ports:
      - "3306:3306"
  torus-metadata:
    restart: always
    depends_on:
      - mysql
      - ipfs
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.development
    ports:
      - "5051:5051/tcp"
    volumes:
      - .:/app
  ipfs:
    image: ipfs/go-ipfs
    ports: 
      - "5001:5001/tcp"
